#define SCLEX_JASS 136

#define SCE_JASS_DEFAULT 0
#define SCE_JASS_COMMENT 1
#define SCE_JASS_COMMENTLINE 2
#define SCE_JASS_COMMENTFLAG 3
#define SCE_JASS_NUMBER 4
#define SCE_JASS_WORD 5
#define SCE_JASS_STRING 6
#define SCE_JASS_CHARACTER 7
#define SCE_JASS_PREPROCESSOR 8
#define SCE_JASS_OPERATOR 9
#define SCE_JASS_IDENTIFIER 10
#define SCE_JASS_STRINGEOL 11
#define SCE_JASS_RUNTEXTMACRO 12
#define SCE_JASS_WORD2 13
#define SCE_JASS_WORD3 14
#define SCE_JASS_WORD4 15
#define SCE_JASS_WORD5 16
#define SCE_JASS_WORD6 17
#define SCE_JASS_WORD7 18
#define SCE_JASS_LUA_DEFAULT 19
#define SCE_JASS_LUA_COMMENT 20
#define SCE_JASS_LUA_COMMENTLINE 21
#define SCE_JASS_LUA_COMMENTDOC 22
#define SCE_JASS_LUA_NUMBER 23
#define SCE_JASS_LUA_WORD 24
#define SCE_JASS_LUA_STRING 25
#define SCE_JASS_LUA_CHARACTER 26
#define SCE_JASS_LUA_LITERALSTRING 27
#define SCE_JASS_LUA_PREPROCESSOR 28
#define SCE_JASS_LUA_OPERATOR 29
#define SCE_JASS_LUA_IDENTIFIER 30
#define SCE_JASS_LUA_STRINGEOL 31
#define SCE_JASS_LUA_LABEL 32

#define SCE_JASS_LUA_IMPORT_FALG 33

#define SCE_JASS_LUA_NAME 34
#define SCE_JASS_LUA_KEY 35

#define SCE_JASS_LUA_WORD2 36
#define SCE_JASS_LUA_WORD3 37
#define SCE_JASS_LUA_WORD4 38
#define SCE_JASS_LUA_WORD5 39
#define SCE_JASS_LUA_WORD6 40
#define SCE_JASS_LUA_WORD7 41
#define SCE_JASS_NMAX 41
